In [1]:
import numpy as np

In [5]:
print(np.array([1, 2, 3]))
print(np.array([(1, 2, 3), (4, 5, 6)]))

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [6]:
print(np.ones((3, 4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [10]:
print(np.full((2, 30), 5))

[[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]]


In [27]:
print(np.random.rand(2, 3))

[[0.87397033 0.53140645 0.80121919]
 [0.50316265 0.36995394 0.23973161]]


In [28]:
print(np.random.rand(2, 3) * 100)

[[25.98961768 21.95634131 32.93089139]
 [32.276357   77.09801099 68.31520595]]


In [25]:
print(np.random.randint(10, size=(2, 3)))

[[6 2 8]
 [9 1 3]]


In [32]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.ndim)

2


In [57]:
arr = np.array([250, 256, 256, 256, 256])
b = arr.view(dtype="int8")
print(arr)
print(b)

[250 256 256 256 256]
[-6  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  1  0  0  0  0  0  0
  0  1  0  0  0  0  0  0  0  1  0  0  0  0  0  0]


In [58]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr.flatten())

[1 2 3 4 5 6 7 8]


In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.T)
print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.reshape(4, 3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [73]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.resize(3, 5)
print(arr)

print(np.resize(arr, (4, 5)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12  0  0  0]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12  0  0  0]
 [ 1  2  3  4  5]]


In [83]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(np.delete(arr, [1, 3]))

[1 3 5 6 7]


In [88]:
arr = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9,10], [11, 12]], [[13, 14], [15, 16], [17, 18]]])
print(np.delete(arr, 1, axis=2))

[[[ 1]
  [ 3]
  [ 5]]

 [[ 7]
  [ 9]
  [11]]

 [[13]
  [15]
  [17]]]
