# #2 Linear Regression Using Gradient Descent

In [4]:
from os.path import split

import numpy as np


def linear_regression_gradient_descent(X: np.ndarray, y: np.ndarray, alpha: float, iterations: int) -> np.ndarray:
    """
    Perform linear regression using gradient descent.

    Args:
        X: Feature matrix of shape (m, n) where first column is all ones (for intercept)
        y: Target vector of shape (m,)
        alpha: Learning rate
        iterations: Number of gradient descent iterations

    Returns:
        Learned weights as a 1D array of shape (n,)
    """
    m, n = X.shape
    y = y.reshape(-1, 1)  # Ensure y is a column vector
    theta = np.zeros((n, 1))  # Initialize weights to zeros

    # Your code here: implement gradient descent
    for i in range(iterations):
        grad = (X.T @ (X @ theta - y)) / m
        theta -= alpha * grad
    return theta.flatten()

In [5]:
# Test Case 1
print(
    np.round(linear_regression_gradient_descent(np.array([[1, 1], [1, 2], [1, 3]]), np.array([3, 5, 7]), 0.1, 1000), 4))

# Expected Output:
# [1. 2.]

[1. 2.]


# #3 Feature Scaling Implementation

In [39]:
def feature_scaling(data: np.ndarray) -> (np.ndarray, np.ndarray):
    # Your code here
    means = np.mean(data, axis=0)
    stds = np.std(data, axis=0)
    standardized_data = (data - means) / stds

    max = np.max(data, axis=0)
    min = np.min(data, axis=0)
    normalized_data = (data - min) / (max - min)

    return standardized_data, normalized_data

In [41]:
# Test Case 1
print(feature_scaling(np.array([[1, 2], [3, 4], [5, 6]])))

# Expected Output:
# ([[-1.2247, -1.2247], [0.0, 0.0], [1.2247, 1.2247]], [[0.0, 0.0], [0.5, 0.5], [1.0, 1.0]])

(array([[-1.22474487, -1.22474487],
       [ 0.        ,  0.        ],
       [ 1.22474487,  1.22474487]]), array([[0. , 0. ],
       [0.5, 0.5],
       [1. , 1. ]]))


# #4 Random Shuffle of Dataset

In [111]:
import numpy as np


def shuffle_data(X, y, seed=None):
    # Your code here
    rng = np.random.default_rng(seed=seed)
    indicies = np.arange(len(X))
    rng.shuffle(indicies)

    return X[indicies], y[indicies]

In [103]:
print(shuffle_data(np.array([[1, 2], [3, 4], [5, 6], [7, 8]]), np.array([1, 2, 3, 4]), seed=42))

(array([[7, 8],
       [5, 6],
       [3, 4],
       [1, 2]]), array([4, 3, 2, 1]))


Моё решение не зачлось, хотя правильное. Решение от Deep-ML:

In [114]:
import numpy as np


def shuffle_data(X, y, seed=None):
    # Your code here
    if seed:
        np.random.seed(seed)

    indicies = np.arange(X.shape[0])
    np.random.shuffle(indicies)

    return X[indicies], y[indicies]

In [115]:
print(shuffle_data(np.array([[1, 2], [3, 4], [5, 6], [7, 8]]), np.array([1, 2, 3, 4]), seed=42))

TypeError: 'int' object is not callable

# #5 Batch Iterator for Dataset

In [205]:
import numpy as np


def batch_iterator(X, y=None, batch_size=64):
    # Your code here
    quantity = X.shape[0] // batch_size
    indicies = np.arange(X.shape[0])[quantity::quantity]

    splits_X = np.split(X, indicies)
    if y is not None:
        splits_y = np.split(y, indicies)
        return [list(pair) for pair in zip(splits_X, splits_y)]
    return splits_X

In [206]:
print(batch_iterator(np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]), np.array([1, 2, 3, 4, 5]), batch_size=2))

[[array([[1, 2],
       [3, 4]]), array([1, 2])], [array([[5, 6],
       [7, 8]]), array([3, 4])], [array([[ 9, 10]]), array([5])]]


# #6 One-Hot Encoding of Nominal Values

In [235]:
import numpy as np


def to_categorical(x, n_col=None):
    # Your code here
    if n_col is None:
        n_col = np.max(x) + 1
    one_hot_values = np.zeros((x.shape[0], n_col))

    one_hot_values[np.arange(x.shape[0]), x] = 1
    return one_hot_values

In [236]:
print(to_categorical(np.array([0, 1, 2, 1, 0])))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


# #7 Calculate Accuracy Score

In [242]:
import numpy as np


def accuracy_score(y_true, y_pred):
    # Your code here
    numerator = np.sum(y_true == y_pred)
    return numerator / y_true.shape[0]


In [243]:
print(accuracy_score(np.array([1, 0, 1, 1, 0, 1]), np.array([1, 0, 0, 1, 0, 1])))

0.8333333333333334


# #8 Implement Ridge Regression Loss Function

In [264]:
import numpy as np


def ridge_loss(X: np.ndarray, w: np.ndarray, y_true: np.ndarray, alpha: float) -> float:
    # Your code here
    return np.sum(np.power((X @ w - y_true), 2)) / X.shape[0] + alpha * np.sum(np.power(w, 2))


In [268]:
X = np.array([[1, 1], [2, 1], [3, 1], [4, 1]])
W = np.array([0.2, 2])
y = np.array([2, 3, 4, 5])
alpha = 0.1

output = ridge_loss(X, W, y, alpha)
print(output)

2.204


# #9 Linear Kernel Function

In [269]:
import numpy as np


def kernel_function(x1, x2):
    # Your code here
    return np.sum(x1.T @ x2)

In [270]:
x1 = np.array([1, 2, 3])
x2 = np.array([4, 5, 6])
result = kernel_function(x1, x2)
print(result)

32


# #10 Implement Precision Metric

In [283]:
import numpy as np


def precision(y_true, y_pred):
    # Your code here
    return np.sum((y_pred & 1) & (y_true & 1)) / np.sum(y_pred & 1)

In [284]:
import numpy as np

y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 1, 0, 0, 1])
result = precision(y_true, y_pred)
print(result)

1.0


# #11 Implement Recall Metric in Binary Classification

In [296]:
import numpy as np


def recall(y_true, y_pred):
    """
    Calculate the recall metric for binary classification.

    Args:
        y_true: Array of true binary labels (0 or 1)
        y_pred: Array of predicted binary labels (0 or 1)

    Returns:
        Recall value as a float
    """
    # Your code here
    tp = np.sum((y_pred == 1) & (y_true == 1))
    fn = np.sum((y_pred == 0) & (y_true == 1))
    return 0 if tp + fn == 0 else tp / (tp + fn)

In [297]:
y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 1, 0, 0, 1])
print(round(recall(y_true, y_pred), 3))

0.75


# #12 Implement F-Score Calculation for Binary Classification

In [318]:
import numpy as np

def f_score(y_true, y_pred, beta):
    """
    Calculate F-Score for a binary classification task.

    :param y_true: Numpy array of true labels
    :param y_pred: Numpy array of predicted labels
    :param beta: The weight of precision in the harmonic mean
    :return: F-Score rounded to three decimal places
    """


    tp = np.sum((y_pred == 1) & (y_true == 1))
    fp = np.sum((y_pred == 1) & (y_true == 0))
    fn = np.sum((y_pred == 0) & (y_true == 1))

    precision = tp / (tp + fp)
    recall = tp / (tp + fn)
    denominator = (beta ** 2 * precision + recall)
    f_beta = (1 + beta ** 2) * precision * recall / denominator if denominator != 0 else 0

    return np.round(f_beta, decimals=3)

In [319]:
import numpy as np

y_true = np.array([1, 0, 1, 1, 0, 1])
y_pred = np.array([1, 0, 1, 0, 0, 1])
beta = 1
print(f_score(y_true, y_pred, beta))

0.857


# #13 Implement Gini Impurity Calculation for a Set of Classes

Формула Gini Impurity:
$$Gini = 1 - \sum_{i=1}^n (p_i)^2,$$
где:\
$p_i$ — вероятность (доля) каждого класса $i$ в текущем узле,\
$n$ — всего классов в текущем узле.

In [324]:
import numpy as np

def gini_impurity(y):
    """
    Calculate Gini Impurity for a list of class labels.

    :param y: List of class labels
    :return: Gini Impurity rounded to three decimal places
    """

    classes = np.unique(y)
    p_i = []
    for cur_class in classes:
        p_i.append(np.sum(y == cur_class) / len(y))

    val = 1 - np.sum(np.power(p_i, 2))
    return round(val, 3)

In [325]:
y = [0, 0, 0, 0, 1, 1, 1, 1]
print(gini_impurity(y))

[0 1]
[np.float64(0.5), np.float64(0.5)]
0.5


# #14 Calculate R-squared for Regression Analysis

In [328]:
import numpy as np

def r_squared(y_true, y_pred):
	# Write your code here
    mean_y_true = np.sum(y_true) / y_true.shape[0]
    numerator = np.sum(np.power(y_true - y_pred, 2))
    denominator = np.sum(np.power(y_true - mean_y_true, 2))
    return 1 - np.round(numerator / denominator, decimals=3)

In [329]:
import numpy as np
y_true = np.array([1, 2, 3, 4, 5])
y_pred = np.array([1, 2, 3, 4, 5])
print(r_squared(y_true, y_pred))

1.0


# #15 Calculate Root Mean Square Error (RMSE)

In [336]:
import numpy as np

def rmse(y_true, y_pred):
	# Write your code here
    if y_true.shape != y_pred.shape \
            or y_true.size == 0 or y_pred.size == 0 \
            or not isinstance(y_true, np.ndarray) or not isinstance(y_pred, np.ndarray):
        return None

    rmse = np.power((y_pred - y_true), 2).mean()**0.5
    return round(rmse,3)

In [337]:
# Test Case 1: Normal Case
y_true1 = np.array([3, -0.5, 2, 7])
y_pred1 = np.array([2.5, 0.0, 2, 8])
print(rmse(y_true1, y_pred1))

0.612
