In [60]:
import numpy as np
import sys
print("sys.executable:", sys.executable)
%who

sys.executable: D:\Anaconda3\envs\machine_learning\python.exe
a	 arr	 b	 c	 d	 diag_matrix	 jupyter_extract_zip	 main_matrix	 np	 
os	 pis	 rev_diag_matrix	 sys	 trig_identity	 u	 v	 x	 x1	 
x2	 x3	 x4	 y	 


In [61]:
a = [1, 2, 3]
b = np.array(a, dtype="float64")
print(type(b), type(a))
print(b)

<class 'numpy.ndarray'> <class 'list'>
[1. 2. 3.]


**Если типы разные, идёт каст к одному типу**

In [62]:
a = [1, 2, "str"]
b = np.array(a)
print("For list: {} \nFor numpy: {}".format(type(a[0]), type(b[0])))

For list: <class 'int'> 
For numpy: <class 'numpy.str_'>


In [63]:
d = np.array([1, 2, 3])
d

array([1, 2, 3])

In [64]:
set(dir(b)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',

**Размер массива в байтах**

In [65]:
arr = np.array([1, 2, 3, 4, 5], dtype="int32")
arr.nbytes

20

**Количественные характеристики ndarray**

In [66]:
arr = np.array([[[1, 2, 3, 4],
                 [2, 3 ,4 ,5],
                 [3, 4, 5, 6]],
                [[1, 2, 3, 4],
                 [2, 3, 4, 5],
                 [3, 4, 5, 6]]])

print(arr)
print("\nlen(arr) = {} -- количество элементов по первой оси".format(len(arr)))
print("arr.size = {} -- всего элементов в матрице".format(arr.size))
print("arr.ndim = {} -- размерность матрицы".format(arr.ndim))
print("arr.shape = {} -- количество элементов по каждой оси".format(arr.shape))

[[[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]]

len(arr) = 2 -- количество элементов по первой оси
arr.size = 24 -- всего элементов в матрице
arr.ndim = 3 -- размерность матрицы
arr.shape = (2, 3, 4) -- количество элементов по каждой оси


**Индексы**

In [67]:
a = np.array([1, 2, 3, 4])
print(a)
print("first el = {} \nlast el = {} \nprevlast el = {}".format(a[0], a[-1], a[-2]))

[1 2 3 4]
first el = 1 
last el = 4 
prevlast el = 3


In [68]:
a[0] = 10
print(a)

[10  2  3  4]


**Задача 1**: Создать numpy-массив, состоящий из первых четырёх простых чисел, выведите его тип и размер.

In [69]:
arr = np.array([2, 3, 5, 7])
print("array: {}".format(arr))
print(arr.dtype)
print(type(arr))
print(arr.shape)
print(arr.nbytes)

array: [2 3 5 7]
int64
<class 'numpy.ndarray'>
(4,)
32


## Создание массивов

In [70]:
a = np.zeros(7)
b = np.ones(7, dtype="int16")
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


**Часто нужно создать массив такой же как другой**

In [71]:
c = np.zeros_like(b)
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [72]:
c = np.zeros(7)
c

array([0., 0., 0., 0., 0., 0., 0.])

**Функция np.arange подобна range**

In [73]:
a = np.arange(5, 21, 3)
b = np.arange(1., 7, 1)
c = np.arange(1, 12)
d = np.arange(5)
print(a, "\n", b, "\n", c, "\n", d, sep="")

[ 5  8 11 14 17 20]
[1. 2. 3. 4. 5. 6.]
[ 1  2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4]


**С помощью linspace можно задать последовательность чисел с постоянных шагом. Границы включаются. Последний элемент - число точек**

In [74]:
a = np.linspace(1, 15, 2)
b = np.linspace(1, 20, 10)
print(a)
print(b)

[ 1. 15.]
[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


**Задача 2**: создать и вывести последовательность чисел от 10 до 32 с постоянным шагом, длина последовательности - 12. Чему равен шаг?

In [75]:
a = np.linspace(10, 32, 12)
print(a)
print(a[1] - a[0])

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
2.0


**Последовательность чисел с постоянным шагом по логарифмической шкале от $10^0$ до $10^3$**

In [76]:
a = np.logspace(0, 3, 12)
print(a)

[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


## Операции над одномерными массивами

**Арифметические операции производятся поэлементарно**

In [145]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a)
print(b)

print("sum: {}".format(a + b))
print("sub: {}:".format(a - b))
print("mult: {}".format(a * b))
print("div: {}".format(a / b))

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
sum: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
sub: [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]:
mult: [  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
div: [-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


**Один из операндов может быль скаляром, а не массивом**

In [78]:
print(5 * a)
print(10 + b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [79]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


In [80]:
type(np.cos)

numpy.ufunc

In [81]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [82]:
print(b)
np.log(b)

[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]


C:\Users\SashaCurry\AppData\Local\Temp\ipykernel_117260\1913047956.py:2: RuntimeWarning: invalid value encountered in log
  np.log(b)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [83]:
print(a > b)
print(a == b)
print(a >= 10)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


In [84]:
# Кванторы всеобщности и существования
c = np.arange(0., 20)
print(c)
print(np.any(c == 0))
print(np.all(c == 0))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
True
False


In [85]:
print(np.array([0, 0, 1, -1]) / np.array([1, 0, 0, 0]))

[  0.  nan  inf -inf]


C:\Users\SashaCurry\AppData\Local\Temp\ipykernel_117260\948646954.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([0, 0, 1, -1]) / np.array([1, 0, 0, 0]))
C:\Users\SashaCurry\AppData\Local\Temp\ipykernel_117260\948646954.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array([0, 0, 1, -1]) / np.array([1, 0, 0, 0]))


In [86]:
print(b)
print(b.cumsum())

[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
[  -2.   -6.  -12.  -20.  -30.  -42.  -56.  -72.  -90. -110. -132.]


**Сортировка**

In [143]:
a = np.array([1, 2, 3, -5, -6, -7])
print(np.sort(a)) # Don't changed current array
print(a)
print(a.sort()) # Changed current array
print(a)

[-7 -6 -5  1  2  3]
[ 1  2  3 -5 -6 -7]
None
[-7 -6 -5  1  2  3]


**Union arrays**

In [146]:
print(a)
print(b)
print(np.hstack((a, b, 5*b)))

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
[   3.    6.    9.   12.   15.   18.   21.   24.   27.   30.   33.   -2.
   -4.   -6.   -8.  -10.  -12.  -14.  -16.  -18.  -20.  -22.  -10.  -20.
  -30.  -40.  -50.  -60.  -70.  -80.  -90. -100. -110.]


**Расщепление массива**

In [89]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6])
print(x1)
print(x2)
print(x3)
print(x4)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5]
[6]
[7 8 9]


**Methods append, delete, insert**

In [90]:
print(np.delete(a, [2, 4, 1]))
print(a)

[1 4 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [91]:
print(a)
print(np.insert(a, 2, [-1, -1]))

[1 2 3 4 5 6 7 8 9]
[ 1  2 -1 -1  3  4  5  6  7  8  9]


In [92]:
print(a)
print(np.append(a, [-1, -2, -3]))

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 -1 -2 -3]


## Индексирование массивов и срезы

In [93]:
# Reverse array
print(a)
print(a[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [94]:
# Subarray
print(a)
print(a[1:5])

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]


In [95]:
# При работе с диапазонами используется один и тот же участок памяти
b = np.array([1, 2, 3, 4, 5])
c = b[0 : 3]
c[0] = 100
print(c)
print(b)

[100   2   3]
[100   2   3   4   5]


In [96]:
print(a)
a[0: 10: 3] = -10
print(a)

[1 2 3 4 5 6 7 8 9]
[-10   2   3 -10   5   6 -10   8   9]


**Метод copy для копирования массива в новый участок памяти**

In [97]:
b = a.copy()
b[0] = 50
print(a)
print(b)

[-10   2   3 -10   5   6 -10   8   9]
[ 50   2   3 -10   5   6 -10   8   9]


In [98]:
# Обращение к нескольким массивам индекса
print(a)
print(a[[5, 3, 1]])

[-10   2   3 -10   5   6 -10   8   9]
[  6 -10   2]


**Задача 3**:
- Создать массив чисел от $-4\Pi$ до $4\Pi$ включительно, количество точек 100;
- Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива;
- С помощью *np.all* проверить, что все элементы равны единице.

In [99]:
pis = np.linspace(-4 * np.pi, 4 * np.pi, 100)
# print(pis)
trig_identity = (np.sin(pis)**2 + np.cos(pis)**2).round()
print(trig_identity)
print(np.all(trig_identity == 1.))


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
True


## Двумерные массивы

In [100]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


**Обращение по индексу**

In [101]:
print(a)
print(a[0][0])
print(a[0, 0])

[[1 2]
 [3 4]]
1
1


**Атрибуту shape можно присвоить новое значение. В итоге будет работа с новой матрицей**

In [102]:
b = np.arange(0, 20)
print(b)
b.shape = (2, 10)
print(b)
b.shape = (4, 5)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


**Стягивание многомерного массива в одномерный**

In [103]:
print(b.ravel())
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


**Единичная матрица**

In [104]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Произвольные диагональные матрицы**

In [105]:
d = np.diag([1, 2, 3, 4])
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


**Задача 4**: Создать квадратную матриуц размером 8, на главной диагонали арифметическая прогрессия с шагом 3 (начиная с 3), а на побочной -1. Остальные элементы 0.

In [106]:
print(-1 * np.eye(8, dtype="int")[::-1] + np.diag(range(3, 3*8 + 1, 3)))

[[ 3  0  0  0  0  0  0 -1]
 [ 0  6  0  0  0  0 -1  0]
 [ 0  0  9  0  0 -1  0  0]
 [ 0  0  0 12 -1  0  0  0]
 [ 0  0  0 -1 15  0  0  0]
 [ 0  0 -1  0  0 18  0  0]
 [ 0 -1  0  0  0  0 21  0]
 [-1  0  0  0  0  0  0 24]]


In [107]:
diag_matrix = np.diag(np.arange(3, 3*8 + 1, 3))
rev_diag_matrix = [-1 * lst[::-1] for lst in np.eye(8, dtype="int")]
main_matrix = diag_matrix + rev_diag_matrix
print(main_matrix)

[[ 3  0  0  0  0  0  0 -1]
 [ 0  6  0  0  0  0 -1  0]
 [ 0  0  9  0  0 -1  0  0]
 [ 0  0  0 12 -1  0  0  0]
 [ 0  0  0 -1 15  0  0  0]
 [ 0  0 -1  0  0 18  0  0]
 [ 0 -1  0  0  0  0 21  0]
 [-1  0  0  0  0  0  0 24]]


**Умножение матриц**

In [108]:
a = 5 * np.ones((5, 5))
b = np.eye(5) + 1
print(a)
print()
print(b)

[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [109]:
# Поэлементное умножение
print(a * b, '\n')

# Матричное умножение
print(a @ b, '\n')
print(a.dot(b))

[[10.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 10.  5.  5.]
 [ 5.  5.  5. 10.  5.]
 [ 5.  5.  5.  5. 10.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]] 

[[30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]
 [30. 30. 30. 30. 30.]]


**Двумерные массивы, зависящие только от одного индекса**: $x_{ij} = u_j$, $y_{ij} = v_i$

In [118]:
u = np.linspace(1, 4, 4)
v = np.linspace(4, 8, 3)
print(u)
print(v)

[1. 2. 3. 4.]
[4. 6. 8.]


In [119]:
x, y = np.meshgrid(u, v)
print(x, '\n')
print(y)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]] 

[[4. 4. 4. 4.]
 [6. 6. 6. 6.]
 [8. 8. 8. 8.]]


In [123]:
# То же самое, что и shape
print(x.reshape(12))

[1. 2. 3. 4. 1. 2. 3. 4. 1. 2. 3. 4.]


**Задача 5**: Отобразить вектор размера 100, в котором вычёркивается *x*, если *x* --- составное (т.е. не является простым)

In [167]:
array = np.zeros(100, dtype=bool)
array[0] = True
simples = np.empty(0, dtype=int)
for i in range (2, 101):
    is_simple = True
    for simple in simples:
        if i % simple == 0:
            is_simple = False
            break
    if is_simple:
        array[i - 1] = True
        simples = np.append(simples, i)

nums = range(1, 101)
print(list((nums[i], bool(array[i])) for i in range(100)))

[(1, True), (2, True), (3, True), (4, False), (5, True), (6, False), (7, True), (8, False), (9, False), (10, False), (11, True), (12, False), (13, True), (14, False), (15, False), (16, False), (17, True), (18, False), (19, True), (20, False), (21, False), (22, False), (23, True), (24, False), (25, False), (26, False), (27, False), (28, False), (29, True), (30, False), (31, True), (32, False), (33, False), (34, False), (35, False), (36, False), (37, True), (38, False), (39, False), (40, False), (41, True), (42, False), (43, True), (44, False), (45, False), (46, False), (47, True), (48, False), (49, False), (50, False), (51, False), (52, False), (53, True), (54, False), (55, False), (56, False), (57, False), (58, False), (59, True), (60, False), (61, True), (62, False), (63, False), (64, False), (65, False), (66, False), (67, True), (68, False), (69, False), (70, False), (71, True), (72, False), (73, True), (74, False), (75, False), (76, False), (77, False), (78, False), (79, True), (80,

**Маски**

In [169]:
a = np.arange(20)
print(a % 3 == 0)
print(a[a % 3 == 0])

[ True False False  True False False  True False False  True False False
  True False False  True False False  True False]
[ 0  3  6  9 12 15 18]


**След (trace) - сумма диагональных элементов**

In [170]:
b = np.diag(a[a >= 10])
print(b)
print(b.trace())

[[10  0  0  0  0  0  0  0  0  0]
 [ 0 11  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  0  0  0  0  0]
 [ 0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 16  0  0  0]
 [ 0  0  0  0  0  0  0 17  0  0]
 [ 0  0  0  0  0  0  0  0 18  0]
 [ 0  0  0  0  0  0  0  0  0 19]]
145


## Тензоры (многомерные массивы)

In [173]:
X = np.arange(64).reshape(8, 2, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]]

 [[56 57 58 59]
  [60 61 62 63]]]


**Суммы по разным осям**

In [172]:
print(np.sum(X))

2016


In [174]:
print(np.sum(X, axis=0), '\n')
print(np.sum(X, axis=1), '\n')
print(np.sum(X, axis=2), '\n')

[[224 232 240 248]
 [256 264 272 280]] 

[[  4   6   8  10]
 [ 20  22  24  26]
 [ 36  38  40  42]
 [ 52  54  56  58]
 [ 68  70  72  74]
 [ 84  86  88  90]
 [100 102 104 106]
 [116 118 120 122]] 

[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]
 [134 150]
 [166 182]
 [198 214]
 [230 246]] 



In [175]:
print(np.sum(X, axis=(1, 2)))

[ 28  92 156 220 284 348 412 476]


## Линейная алгебра

In [176]:
a = np.array([[2, 1], [2, 3]])
print(a)

[[2 1]
 [2 3]]


**Определитель матрицы**

In [178]:
print(np.linalg.det(a))

4.0


**Обратная матрица**

In [179]:
b = np.linalg.inv(a)
print(b)

[[ 0.75 -0.25]
 [-0.5   0.5 ]]


In [180]:
print(a.dot(b))
print(b.dot(a))

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [183]:
c = np.array([[2, 1], [6, 3]])
print(c)
print(np.linalg.det(c))

[[2 1]
 [6 3]]
0.0


In [185]:
np.linalg.inv(c)

LinAlgError: Singular matrix

**Решение неоднородных линейных уравнений (НЛУ)**
$$A * x = v$$

In [187]:
v = np.array([5, -10])
print(np.linalg.solve(a, v))
print(np.linalg.inv(a).dot(v))

[ 6.25 -7.5 ]
[ 6.25 -7.5 ]


**Собственные вектора матрицы $A$**
$$A * x  = \lambda * x$$

In [188]:
l, u = np.linalg.eig(a)
print(l)
print(u)

[1. 4.]
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


**Собственные значений матрицы $A$ и $A.T$ сопадают**

In [189]:
l, u = np.linalg.eig(a.T)
print(l)
print(u)

[1. 4.]
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]
