In [1]:
import numpy as np

In [3]:
a = [1, 2, 3]
b = np.array(a, dtype="float64")
print(type(b), type(a))
print(b)

<class 'numpy.ndarray'> <class 'list'>
[1. 2. 3.]


**Если типы разные, идёт каст к одному типу**

In [13]:
a = [1, 2, "str"]
b = np.array(a)
print("For list: {} \nFor numpy: {}".format(type(a[0]), type(b[0])))

For list: <class 'int'> 
For numpy: <class 'numpy.str_'>


In [16]:
d = np.array([1, 2, 3])
d

array([1, 2, 3])

In [26]:
set(dir(b)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',

**Размер массива в байтах**

In [27]:
arr = np.array([1, 2, 3, 4, 5], dtype="int32")
arr.nbytes

20

**Количественные характеристики ndarray**

In [4]:
arr = np.array([[[1, 2, 3, 4],
                 [2, 3 ,4 ,5],
                 [3, 4, 5, 6]],
                [[1, 2, 3, 4],
                 [2, 3, 4, 5],
                 [3, 4, 5, 6]]])

print(arr)
print("\nlen(arr) = {} -- количество элементов по первой оси".format(len(arr)))
print("arr.size = {} -- всего элементов в матрице".format(arr.size))
print("arr.ndim = {} -- размерность матрицы".format(arr.ndim))
print("arr.shape = {} -- количество элементов по каждой оси".format(arr.shape))

[[[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]

 [[1 2 3 4]
  [2 3 4 5]
  [3 4 5 6]]]

len(arr) = 2 -- количество элементов по первой оси
arr.size = 24 -- всего элементов в матрице
arr.ndim = 3 -- размерность матрицы
arr.shape = (2, 3, 4) -- количество элементов по каждой оси


**Индексы**

In [84]:
a = np.array([1, 2, 3, 4])
print(a)
print("first el = {} \nlast el = {} \nprevlast el = {}".format(a[0], a[-1], a[-2]))

[1 2 3 4]
first el = 1 
last el = 4 
prevlast el = 3


In [85]:
a[0] = 10
print(a)

[10  2  3  4]


**Задача 1**: Создать numpy-массив, состоящий из первых четырёх простых чисел, выведите его тип и размер.

In [102]:
from sympy import isprime
# arr = np.zeros(4, dtype="int32")
arr = np.array([2, 3, 5, 7])
print("array: {}".format(arr))
print(arr.dtype)
print(type(arr))
print(arr.shape)
print(arr.nbytes)

array: [2 3 5 7]
int64
<class 'numpy.ndarray'>
(4,)
32


## Создание массивов

In [7]:
a = np.zeros(7)
b = np.ones(7, dtype="int16")
print(a)
print(b)

[0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1]


**Часто нужно создать массив такой же как другой**

In [8]:
c = np.zeros_like(b)
c

array([0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [9]:
c = np.zeros(7)
c

array([0., 0., 0., 0., 0., 0., 0.])

**Функция np.arange подобна range**

In [12]:
a = np.arange(5, 21, 3)
b = np.arange(1., 7, 1)
c = np.arange(1, 12)
d = np.arange(5)
print(a, "\n", b, "\n", c, "\n", d, sep="")

[ 5  8 11 14 17 20]
[1. 2. 3. 4. 5. 6.]
[ 1  2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4]


**С помощью linspace можно задать последовательность чисел с постоянных шагом. Границы включаются. Последний элемент - число точек**

In [13]:
a = np.linspace(1, 15, 2)
b = np.linspace(1, 20, 10)
print(a)
print(b)

[ 1. 15.]
[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


**Задача 2**: создать и вывести последовательность чисел от 10 до 32 с постоянным шагом, длина последовательности - 12. Чему равен шаг?

In [15]:
a = np.linspace(10, 32, 12)
print(a)
print(a[1] - a[0])

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32.]
2.0


**Последовательность чисел с постоянным шагом по логарифмической шкале от $10^0$ до $10^3$**

In [17]:
a = np.logspace(0, 3, 12)
print(a)

[   1.            1.87381742    3.51119173    6.57933225   12.32846739
   23.101297     43.28761281   81.11308308  151.9911083   284.80358684
  533.66992312 1000.        ]


## Операции над одномерными массивами

**Арифметические операции производятся поэлементарно**

In [28]:
a = np.linspace(3, 33, 11)
b = np.linspace(-2, -22, 11)
print(a)
print(b)

print("sum: {}".format(a + b))
print("sub: {}:".format(a - b))
print("mult: {}".format(a * b))
print("div: {}".format(a / b))

[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33.]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
sum: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
sub: [ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55.]:
mult: [  -6.  -24.  -54.  -96. -150. -216. -294. -384. -486. -600. -726.]
div: [-1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5 -1.5]


**Один из операндов может быль скаляром, а не массивом**

In [21]:
print(5 * a)
print(10 + b)

[ 15.  30.  45.  60.  75.  90. 105. 120. 135. 150. 165.]
[  8.   6.   4.   2.   0.  -2.  -4.  -6.  -8. -10. -12.]


In [22]:
print((a + b) ** 2)
print(2 ** (a + b))

[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100. 121.]
[2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01 6.400e+01 1.280e+02
 2.560e+02 5.120e+02 1.024e+03 2.048e+03]


In [23]:
type(np.cos)

numpy.ufunc

In [24]:
np.cos(a)

array([-0.9899925 ,  0.96017029, -0.91113026,  0.84385396, -0.75968791,
        0.66031671, -0.54772926,  0.42417901, -0.29213881,  0.15425145,
       -0.01327675])

In [29]:
print(b)
np.log(b)

[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]


/tmp/ipykernel_19237/1913047956.py:2: RuntimeWarning: invalid value encountered in log
  np.log(b)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [30]:
print(a > b)
print(a == b)
print(a >= 10)

[ True  True  True  True  True  True  True  True  True  True  True]
[False False False False False False False False False False False]
[False False False  True  True  True  True  True  True  True  True]


In [36]:
# Кванторы всеобщности и существования
c = np.arange(0., 20)
print(c)
print(np.any(c == 0))
print(np.all(c == 0))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]
True
False


In [37]:
print(np.array([0, 0, 1, -1]) / np.array([1, 0, 0, 0]))

[  0.  nan  inf -inf]


/tmp/ipykernel_19237/948646954.py:1: RuntimeWarning: divide by zero encountered in divide
  print(np.array([0, 0, 1, -1]) / np.array([1, 0, 0, 0]))
/tmp/ipykernel_19237/948646954.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array([0, 0, 1, -1]) / np.array([1, 0, 0, 0]))


In [38]:
print(b)
print(b.cumsum())

[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
[  -2.   -6.  -12.  -20.  -30.  -42.  -56.  -72.  -90. -110. -132.]


**Сортировка**

In [41]:
a = np.array([1, 2, 3, -5, -6, -7])
print(np.sort(a)) # Don't changed current array
print(a)
print(a.sort()) # Changed current array
print(a)

[-7 -6 -5  1  2  3]
[ 1  2  3 -5 -6 -7]
None
[-7 -6 -5  1  2  3]


**Union arrays**

In [43]:
print(a)
print(b)
print(np.hstack((a, b, 5*b)))

[-7 -6 -5  1  2  3]
[ -2.  -4.  -6.  -8. -10. -12. -14. -16. -18. -20. -22.]
[  -7.   -6.   -5.    1.    2.    3.   -2.   -4.   -6.   -8.  -10.  -12.
  -14.  -16.  -18.  -20.  -22.  -10.  -20.  -30.  -40.  -50.  -60.  -70.
  -80.  -90. -100. -110.]


**Расщепление массива**

In [46]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
x1, x2, x3, x4 = np.hsplit(a, [3, 5, 6])
print(x1)
print(x2)
print(x3)
print(x4)

[1 2 3 4 5 6 7 8 9]
[1 2 3]
[4 5]
[6]
[7 8 9]


**Methods append, delete, insert**

In [48]:
print(np.delete(a, [2, 4, 1]))
print(a)

[1 4 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [49]:
print(a)
print(np.insert(a, 2, [-1, -1]))

[1 2 3 4 5 6 7 8 9]
[ 1  2 -1 -1  3  4  5  6  7  8  9]


In [50]:
print(a)
print(np.append(a, [-1, -2, -3]))

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 -1 -2 -3]


## Индексирование массивов и срезы

In [51]:
# Reverse array
print(a)
print(a[::-1])

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [52]:
# Subarray
print(a)
print(a[1:5])

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]


In [55]:
# При работе с диапазонами используется один и тот же участок памяти
b = np.array([1, 2, 3, 4, 5])
c = b[0 : 3]
c[0] = 100
print(c)
print(b)

[100   2   3]
[100   2   3   4   5]


In [57]:
print(a)
a[0: 10: 3] = -10
print(a)

[1 2 3 4 5 6 7 8 9]
[-10   2   3 -10   5   6 -10   8   9]


**Метод copy для копирования массива в новый участок памяти**

In [58]:
b = a.copy()
b[0] = 50
print(a)
print(b)

[-10   2   3 -10   5   6 -10   8   9]
[ 50   2   3 -10   5   6 -10   8   9]


In [60]:
# Обращение к нескольким массивам индекса
print(a)
print(a[[5, 3, 1]])

[-10   2   3 -10   5   6 -10   8   9]
[  6 -10   2]


**Задача 3**:
- Создать массив чисел от $-4\Pi$ до $4\Pi$ включительно, количество точек 100;
- Посчитать сумму поэлементных квадратов синуса и косинуса для данного массива;
- С помощью *np.all* проверить, что все элементы равны единице.

In [88]:
pis = np.linspace(-4 * np.pi, 4 * np.pi, 100)
# print(pis)
trig_identity = (np.sin(pis)**2 + np.cos(pis)**2).round()
print(trig_identity)
print(np.all(trig_identity == 1.))


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
True


## Двумерные массивы

In [89]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


**Обращение по индексу**

In [91]:
print(a)
print(a[0][0])
print(a[0, 0])

[[1 2]
 [3 4]]
1
1


**Атрибуту shape можно присвоить новое значение. В итоге будет работа с новой матрицей**

In [93]:
b = np.arange(0, 20)
print(b)
b.shape = (2, 10)
print(b)
b.shape = (4, 5)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


**Стягивание многомерного массива в одномерный**

In [94]:
print(b.ravel())
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


**Единичная матрица**

In [95]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Произвольные диагональные матрицы**

In [99]:
d = np.diag([1, 2, 3, 4])
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


**Задача 4**: Создать квадратную матриуц размером 8, на главной диагонали арифметическая прогрессия с шагом 3 (начиная с 3), а на побочной -1. Остальные элементы 0.

In [165]:
diag_matrix = np.diag(np.arange(3, 3*8 + 1, 3))
rev_diag_matrix = [-1 * lst[::-1] for lst in np.eye(8, dtype="int")]
main_matrix = diag_matrix + rev_diag_matrix
print(main_matrix)

[[ 3  0  0  0  0  0  0 -1]
 [ 0  6  0  0  0  0 -1  0]
 [ 0  0  9  0  0 -1  0  0]
 [ 0  0  0 12 -1  0  0  0]
 [ 0  0  0 -1 15  0  0  0]
 [ 0  0 -1  0  0 18  0  0]
 [ 0 -1  0  0  0  0 21  0]
 [-1  0  0  0  0  0  0 24]]


In [189]:
print(-1 * np.eye(8, dtype="int")[::-1] + np.diag(range(3, 3*8 + 1, 3)))

[[ 3  0  0  0  0  0  0 -1]
 [ 0  6  0  0  0  0 -1  0]
 [ 0  0  9  0  0 -1  0  0]
 [ 0  0  0 12 -1  0  0  0]
 [ 0  0  0 -1 15  0  0  0]
 [ 0  0 -1  0  0 18  0  0]
 [ 0 -1  0  0  0  0 21  0]
 [-1  0  0  0  0  0  0 24]]
