In [3]:
import torch

In [32]:
"""
torch.tensor() ==> numpy.array()
"""

# torch.tensor([2, 3])
# torch.tensor([[2, 3], [4, 5]])
# torch.tensor([[2, 3], [4, 5]], dtype=torch.int32)
# torch.tensor([[2, 3], [4, 5]], dtype=torch.float32)
# torch.tensor([[2, 3], [4, 5]], dtype=torch.float32, requires_grad=True)
# torch.tensor([[2, 3], [4, 5]], requires_grad=True)
torch.tensor([[2, 3], [4, 5]], device=torch.device('cuda:0'))

tensor([[2, 3],
        [4, 5]], device='cuda:0')

In [ ]:
# Свойства и методы tensor
from numpy import require
tensor = torch.tensor(([[[2, 3], [4, 5]], [[6, 7], [8, 9]]]),
                      dtype=torch.float32,
                      requires_grad=True)

# tensor.dtype

# tensor.shape
# tensor.size()

# tensor.ndim

# tensor[0, 0, 0]
# type(tensor[0, 0, 0])

# tensor[0, 0, 0].item()
# type(tensor[0, 0, 0].item())

float

In [33]:
# Создание массивов разного размера

# tensor = torch.zeros([2, 3, 2])
# tensor = torch.zeros([2, 3, 2], dtype=torch.int32)

# tensor = torch.ones([2, 3, 2])

# tensor = torch.zeros_like(tensor)
# tensor = torch.full_like(tensor, 7)

print(tensor)
type(tensor)

tensor([[[7., 7.],
         [7., 7.],
         [7., 7.]],

        [[7., 7.],
         [7., 7.],
         [7., 7.]]])


torch.Tensor

In [34]:
# Одномерный тензор в указанном диапазоне с указанным шагом
torch.arange(2, 10, 0.5)

tensor([2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000, 5.0000, 5.5000, 6.0000,
        6.5000, 7.0000, 7.5000, 8.0000, 8.5000, 9.0000, 9.5000])

In [36]:
torch.diag(torch.tensor([5, 4]))

tensor([[5, 0],
        [0, 4]])

In [37]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [38]:
torch.tril(torch.tensor([[1, 2, 3], [2, 3, 4], [4, 5, 6]]))

tensor([[1, 0, 0],
        [2, 3, 0],
        [4, 5, 6]])

In [43]:
tensor = torch.tensor([1, 2, 3 ,4])

# VIEW создаёт представление данных, не делая копию. Работает только если тензор лежит последовательно в памяти
tensor_1 = tensor.view([4 ,1])

# Сначала пытается сделать представление. Если не получается (данные лежат не последовательно), создаёт копию
tensor_2 = tensor.reshape([2, 2])

print(tensor)
print(tensor_1)
print(tensor_2)

tensor([1, 2, 3, 4])
tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 2],
        [3, 4]])


In [44]:
# Добавление осей

tensor = torch.unsqueeze(tensor, 0)

tensor.shape

torch.Size([1, 4])

In [48]:
# Арифметические операции

tensor = torch.tensor([1, 2, 3, 4, 5])

tensor * 5

tensor + torch.tensor([1, 2, 3, 4, 5])

# tensor + [1, 2, 3, 4, 5]

tensor([ 2,  4,  6,  8, 10])

In [61]:
# Математические функции

tensor = torch.tensor([1, 2, 3, 4, 5, 6], dtype=torch.float32)

# tensor.sum()
# tensor.mean()

tensor = tensor.view([2, 3])
tensor_mean = tensor.mean(dim=1, keepdim=True)

print(tensor)
print(tensor_mean)
print(tensor_mean.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[2.],
        [5.]])
torch.Size([2, 1])


In [64]:
# CPU and GPU

print(torch.cpu.is_available())
print(torch.cuda.is_available())

True
True


In [66]:
tensor = torch.tensor([1., 2., 3.], requires_grad=True)

In [71]:
# tensor = tensor.cpu()
# tensor = tensor.to('cpu')

tensor = tensor.cuda()
# tensor = tensor.cuda('cuda')

tensor

tensor([1., 2., 3.], device='cuda:0', grad_fn=<ToCopyBackward0>)

In [81]:
# PATTERN

device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor = tensor.to(device)
tensor

tensor([1., 2., 3.], device='cuda:0', grad_fn=<ToCopyBackward0>)

In [74]:
# Check CPU or GPU

tensor.device

device(type='cuda', index=0)

In [80]:
tensor_cpu = torch.tensor([1., 2., 3.]).to('cpu')

tensor_cpu

tensor([1., 2., 3.])

In [ ]:
# Тезоры нельзя складывать, когда они нга разных девайсах

# tensor + tensor_cpu

new_tensor = tensor + tensor_cpu.to(device)

new_tensor

tensor([2., 4., 6.], device='cuda:0', grad_fn=<AddBackward0>)

In [86]:
# Тензоры копируются вместе с градиентом

new_tensor = new_tensor.cpu()

new_tensor = new_tensor.cpu().detach()

new_tensor

tensor([2., 4., 6.])